### Cadastrar um Produto
POST https://localhost:5001/api/produto/Create
Content-Type:  application/json

{
    "Nome" : "café é bão",
    "Preco" : 3.5,
    "Quantidade" : 10,
    "Descricao" : "Descrição aqui",
    "Categoria" : {
        "Id" : 123
    }
}

### Listar os Produtos
GET https://localhost:5001/api/produto/list

### Buscar um produto pelo ID
GET https://localhost:5001/api/produto/getbyid/1

###Deletar um produto
DELETE  https://localhost:5001/api/produto/delete/café

### Alterar um produto
PUT  https://localhost:5001/api/produto/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Bolinho alterado",
    "Preco" : 3.5
}
